### ISSUE TITLE
타이머기능 버그픽스

### ISSUE THREAD

**Issue by MartinLeeSJ** [MartinLeeSJ/Monuti#111]
# TODO
- [x] 시간을 설정하는 부분 TimerManager에서 분리해 TimerSettingManager로 코드 옮기기
- [x] UserNotification이 타이머가 멈춰있는 상황에서도 전달되는 상황을 고치기
- [x] ToDo에 쏟은 시간 기록이 실제와 다른 상황 고치기
- [x] 타이머 마지막 세션이 끝났을 때 유저가 직접 끝내기를 눌러야만 종료되는 것 고치기
